stages:
  training_stage:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py

    outs:
      - artifacts/raw_data.csv
      - artifacts/train_data.csv
      - artifacts/test_data.csv
      - artifacts/preprocessor.pkl
      - artifacts/model.pkl
